# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(1501, 1003)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gBox_STOCK_DAY = QtWidgets.QGroupBox(self.centralwidget)
        self.gBox_STOCK_DAY.setEnabled(True)
        self.gBox_STOCK_DAY.setGeometry(QtCore.QRect(0, 0, 701, 631))
        self.gBox_STOCK_DAY.setObjectName("gBox_STOCK_DAY")
        self.btn_Start_Stock_Day = QtWidgets.QPushButton(self.gBox_STOCK_DAY)
        self.btn_Start_Stock_Day.setGeometry(QtCore.QRect(380, 30, 301, 121))
        self.btn_Start_Stock_Day.setObjectName("btn_Start_Stock_Day")
        self.btn_COUNT_STOCK = QtWidgets.QPushButton(self.gBox_STOCK_DAY)
        self.btn_COUNT_STOCK.setGeometry(QtCore.QRect(380, 210, 301, 121))
        self.btn_COUNT_STOCK.setObjectName("btn_COUNT_STOCK")
        self.btn_delete_Files = QtWidgets.QPushButton(self.gBox_STOCK_DAY)
        self.btn_delete_Files.setGeometry(QtCore.QRect(380, 390, 301, 121))
        self.btn_delete_Files.setObjectName("btn_delete_Files")
        self.list_FileList = QtWidgets.QListWidget(self.gBox_STOCK_DAY)
        self.list_FileList.setGeometry(QtCore.QRect(20, 30, 331, 581))
        self.list_FileList.setObjectName("list_FileList")
        self.gBox_TRUCKDAY = QtWidgets.QGroupBox(self.centralwidget)
        self.gBox_TRUCKDAY.setGeometry(QtCore.QRect(750, 0, 731, 961))
        self.gBox_TRUCKDAY.setObjectName("gBox_TRUCKDAY")
        self.btn_TRUCK_DAY = QtWidgets.QPushButton(self.gBox_TRUCKDAY)
        self.btn_TRUCK_DAY.setGeometry(QtCore.QRect(20, 30, 301, 121))
        self.btn_TRUCK_DAY.setObjectName("btn_TRUCK_DAY")
        self.btn_EXPIRED_DATES = QtWidgets.QPushButton(self.gBox_TRUCKDAY)
        self.btn_EXPIRED_DATES.setGeometry(QtCore.QRect(400, 30, 301, 121))
        self.btn_EXPIRED_DATES.setObjectName("btn_EXPIRED_DATES")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.gBox_TRUCKDAY)
        self.calendarWidget.setGeometry(QtCore.QRect(10, 180, 711, 641))
        self.calendarWidget.setObjectName("calendarWidget")
        self.lbl_Calendary = QtWidgets.QLabel(self.gBox_TRUCKDAY)
        self.lbl_Calendary.setGeometry(QtCore.QRect(10, 840, 711, 111))
        self.lbl_Calendary.setText("")
        self.lbl_Calendary.setObjectName("lbl_Calendary")
        self.gBox_DATABASE = QtWidgets.QGroupBox(self.centralwidget)
        self.gBox_DATABASE.setGeometry(QtCore.QRect(10, 690, 721, 221))
        self.gBox_DATABASE.setObjectName("gBox_DATABASE")
        self.btn_ADD_ITEM = QtWidgets.QPushButton(self.gBox_DATABASE)
        self.btn_ADD_ITEM.setGeometry(QtCore.QRect(20, 50, 301, 131))
        self.btn_ADD_ITEM.setObjectName("btn_ADD_ITEM")
        self.btn_CHECK_ITEM = QtWidgets.QPushButton(self.gBox_DATABASE)
        self.btn_CHECK_ITEM.setGeometry(QtCore.QRect(390, 50, 291, 131))
        self.btn_CHECK_ITEM.setObjectName("btn_CHECK_ITEM")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1501, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.gBox_STOCK_DAY.setTitle(_translate("MainWindow", "STOCK DAY"))
        self.btn_Start_Stock_Day.setText(_translate("MainWindow", "STOCK DAY"))
        self.btn_COUNT_STOCK.setText(_translate("MainWindow", "COUNT STOCK"))
        self.btn_delete_Files.setText(_translate("MainWindow", "Delete Files"))
        self.gBox_TRUCKDAY.setTitle(_translate("MainWindow", "EXPIRED DATES"))
        self.btn_TRUCK_DAY.setText(_translate("MainWindow", "TRUCK DAY"))
        self.btn_EXPIRED_DATES.setText(_translate("MainWindow", "EXIPRED DATES"))
        self.gBox_DATABASE.setTitle(_translate("MainWindow", "DATA BASE"))
        self.btn_ADD_ITEM.setText(_translate("MainWindow", "ADD ITEM"))
        self.btn_CHECK_ITEM.setText(_translate("MainWindow", "CHECK ITEM"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
